/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageAirlinerUserInterface;

import Business.Airliner;
import Business.AirlinerCatalog;
import javax.swing.JOptionPane;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rusha
 */
public class CreateAirliner_JPanel extends javax.swing.JPanel {
private AirlinerCatalog airlinercatalog;
private JPanel Display_JPanel;
    /**
     * Creates new form CreateAirliner_JPanel
     */
    public CreateAirliner_JPanel(JPanel Display_JPanel,AirlinerCatalog airlinercatalog) {
        initComponents();
        this.airlinercatalog=airlinercatalog;
        this.Display_JPanel=Display_JPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateAirplane_JLabel = new javax.swing.JLabel();
        AirlinerName_JLabel = new javax.swing.JLabel();
        AirlinerName_JTextField = new javax.swing.JTextField();
        Create_JButton = new javax.swing.JButton();
        Back_JButton = new javax.swing.JButton();
        JLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(660, 500));

        CreateAirplane_JLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CreateAirplane_JLabel.setText("Create Airliner");

        AirlinerName_JLabel.setText("Airliner Name:");

        AirlinerName_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlinerName_JTextFieldActionPerformed(evt);
            }
        });
        AirlinerName_JTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AirlinerName_JTextFieldKeyTyped(evt);
            }
        });

        Create_JButton.setText("Create");
        Create_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_JButtonActionPerformed(evt);
            }
        });

        Back_JButton.setText("Back");
        Back_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back_JButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Create_JButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AirlinerName_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(CreateAirplane_JLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(AirlinerName_JTextField)))
                .addGap(18, 18, 18)
                .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateAirplane_JLabel)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlinerName_JLabel)
                    .addComponent(AirlinerName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Create_JButton)
                    .addComponent(Back_JButton))
                .addContainerGap(306, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AirlinerName_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlinerName_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirlinerName_JTextFieldActionPerformed

    private void Create_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_JButtonActionPerformed
        // TODO add your handling code here:
        try{
            Airliner airliner=airlinercatalog.addAirliner();
            airliner.setAirlinerName(AirlinerName_JTextField.getText());
            if(AirlinerName_JTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Enter the Value");
            }
            else{
                JOptionPane.showMessageDialog(null, "Airliner Created Successfully");
            }
            AirlinerName_JTextField.setText("");
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Invalid values");
        }

    }//GEN-LAST:event_Create_JButtonActionPerformed

    private void Back_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_JButtonActionPerformed
        // TODO add your handling code here:
        Display_JPanel.remove(this);
        CardLayout layout=(CardLayout)Display_JPanel.getLayout();
        layout.previous(Display_JPanel);

    }//GEN-LAST:event_Back_JButtonActionPerformed

    private void AirlinerName_JTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AirlinerName_JTextFieldKeyTyped
        // TODO add your handling code here:
        if(AirlinerName_JTextField.getText().trim().isEmpty()){
        JLabel1.setText("Please add values");
        }
        String AirlinerName=AirlinerName_JTextField.getText();      
        JLabel1.setText("");
    }//GEN-LAST:event_AirlinerName_JTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AirlinerName_JLabel;
    private javax.swing.JTextField AirlinerName_JTextField;
    private javax.swing.JButton Back_JButton;
    private javax.swing.JLabel CreateAirplane_JLabel;
    private javax.swing.JButton Create_JButton;
    private javax.swing.JLabel JLabel1;
    // End of variables declaration//GEN-END:variables
}
