/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MasterScheduleUserInterface;
import Business.CustomerBooking;
import javax.swing.JOptionPane;
import Business.AirplaneCatalog;
import Business.Airplane;
import Business.Airliner;
import Business.Payment;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.CustomerCatalog;
import Business.PaymentCatalog;
/**
 *
 * @author rusha
 */
public class BookingForm_JPanel extends javax.swing.JPanel {
private AirplaneCatalog airplanecatalog;
private JPanel Display_JPanel;
private Airplane airplane;
private Airliner airliner;
private CustomerBooking customerbooking;
private Payment payment;
private CustomerCatalog customercatalog;
private PaymentCatalog paymentcatalog;

    /**
     * Creates new form BookingForm_JPanel
     */
    public BookingForm_JPanel(JPanel Display_JPanel,CustomerCatalog customercatalog) {
        initComponents();
        this.Display_JPanel=Display_JPanel;
        this.customercatalog=customercatalog;
        this.airplane=new Airplane();
        this.customerbooking=new CustomerBooking();
        this.payment=new Payment();
        this.paymentcatalog=new PaymentCatalog();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookingForm_JLabel = new javax.swing.JLabel();
        CustomerName_JLabel = new javax.swing.JLabel();
        CustomerName_JTextField = new javax.swing.JTextField();
        Age_JTextField = new javax.swing.JTextField();
        Age_JLabel = new javax.swing.JLabel();
        AddressLine1_JTextField = new javax.swing.JTextField();
        AddressLine1_JLabel = new javax.swing.JLabel();
        AddressLine2_JTextField = new javax.swing.JTextField();
        AddressLine2_JLabel = new javax.swing.JLabel();
        City_JTextField = new javax.swing.JTextField();
        City_JLabel = new javax.swing.JLabel();
        Zipcode_JLabel = new javax.swing.JLabel();
        Zipcode_JTextField = new javax.swing.JTextField();
        SSN_JLabel = new javax.swing.JLabel();
        SSN_JTextField = new javax.swing.JTextField();
        Sex_JLabel = new javax.swing.JLabel();
        Sex_JTextField = new javax.swing.JTextField();
        EmailID_JLabel = new javax.swing.JLabel();
        EmailID_JTextField = new javax.swing.JTextField();
        PhoneNumber_JLabel = new javax.swing.JLabel();
        PhoneNumber_JTextField = new javax.swing.JTextField();
        Back_JButton = new javax.swing.JButton();
        Next_JButton = new javax.swing.JButton();

        BookingForm_JLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BookingForm_JLabel.setText("Booking Form");

        CustomerName_JLabel.setText("Customer Name:");

        CustomerName_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerName_JTextFieldActionPerformed(evt);
            }
        });

        Age_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_JTextFieldActionPerformed(evt);
            }
        });

        Age_JLabel.setText("Age");

        AddressLine1_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressLine1_JTextFieldActionPerformed(evt);
            }
        });

        AddressLine1_JLabel.setText("Address Line 1");

        AddressLine2_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressLine2_JTextFieldActionPerformed(evt);
            }
        });

        AddressLine2_JLabel.setText("Address Line 2");

        City_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                City_JTextFieldActionPerformed(evt);
            }
        });

        City_JLabel.setText("City");

        Zipcode_JLabel.setText("Zipcode");

        Zipcode_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zipcode_JTextFieldActionPerformed(evt);
            }
        });

        SSN_JLabel.setText("SSN");

        SSN_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSN_JTextFieldActionPerformed(evt);
            }
        });

        Sex_JLabel.setText("Sex");

        Sex_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sex_JTextFieldActionPerformed(evt);
            }
        });

        EmailID_JLabel.setText("Email ID");

        EmailID_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailID_JTextFieldActionPerformed(evt);
            }
        });

        PhoneNumber_JLabel.setText("Phone Number");

        PhoneNumber_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumber_JTextFieldActionPerformed(evt);
            }
        });

        Back_JButton.setText("Back");
        Back_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_JButtonActionPerformed(evt);
            }
        });

        Next_JButton.setText("Next");
        Next_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EmailID_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmailID_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Sex_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sex_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SSN_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SSN_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Zipcode_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Zipcode_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(City_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(City_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddressLine2_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddressLine2_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddressLine1_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddressLine1_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Age_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Age_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BookingForm_JLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CustomerName_JLabel)
                            .addGap(18, 18, 18)
                            .addComponent(CustomerName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNumber_JLabel)
                            .addComponent(Back_JButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Next_JButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PhoneNumber_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(BookingForm_JLabel)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerName_JLabel)
                    .addComponent(CustomerName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age_JLabel)
                    .addComponent(Age_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sex_JLabel))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressLine1_JLabel)
                    .addComponent(AddressLine1_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressLine2_JLabel)
                    .addComponent(AddressLine2_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(City_JLabel)
                    .addComponent(City_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zipcode_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Zipcode_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSN_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSN_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailID_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailID_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumber_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber_JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_JButton)
                    .addComponent(Next_JButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerName_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerName_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerName_JTextFieldActionPerformed

    private void Age_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_JTextFieldActionPerformed

    private void AddressLine1_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressLine1_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressLine1_JTextFieldActionPerformed

    private void AddressLine2_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressLine2_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressLine2_JTextFieldActionPerformed

    private void City_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_City_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_City_JTextFieldActionPerformed

    private void Zipcode_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zipcode_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Zipcode_JTextFieldActionPerformed

    private void SSN_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSN_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSN_JTextFieldActionPerformed

    private void Sex_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sex_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sex_JTextFieldActionPerformed

    private void EmailID_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailID_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailID_JTextFieldActionPerformed

    private void PhoneNumber_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumber_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumber_JTextFieldActionPerformed

    private void Back_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_JButtonActionPerformed
        // TODO add your handling code here:
        Display_JPanel.remove(this);
        CardLayout cardLayout=(CardLayout)Display_JPanel.getLayout();
        cardLayout.previous(Display_JPanel);
    }//GEN-LAST:event_Back_JButtonActionPerformed

    private void Next_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_JButtonActionPerformed
        // TODO add your handling code here:
        
        
            //Airliner airliner=airlinercatalog.addAirliner();
        CustomerBooking customerbooking=customercatalog.addCustomer();
        
        customerbooking.setCustomerName(CustomerName_JTextField.getText());
        customerbooking.setAge(Integer.parseInt(Age_JTextField.getText()));
        customerbooking.setSex(Sex_JTextField.getText());
        customerbooking.setAddressLine1(AddressLine1_JTextField.getText());
        customerbooking.setAddressLine1(AddressLine2_JTextField.getText());
        customerbooking.setCity(City_JTextField.getText());
        customerbooking.setZipcode(Integer.parseInt(Zipcode_JTextField.getText()));
        customerbooking.setSSN(Integer.parseInt(SSN_JTextField.getText()));
        customerbooking.setEmailID(EmailID_JTextField.getText());
        customerbooking.setPhoneNumber(Integer.parseInt(PhoneNumber_JTextField.getText()));
        
            if(CustomerName_JTextField.getText().isEmpty()||Age_JTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Enter the Value");
            }
            else{
                JOptionPane.showMessageDialog(null, "Airliner Created Successfully");
            }
            CustomerName_JTextField.setText("");
            Age_JTextField.setText("");
            Sex_JTextField.setText("");
            AddressLine1_JTextField.setText("");
            AddressLine2_JTextField.setText("");
            City_JTextField.setText("");
            Zipcode_JTextField.setText("");
            SSN_JTextField.setText("");
            EmailID_JTextField.setText("");
            PhoneNumber_JTextField.setText("");
            
            
        //    }
        //catch(Exception e){
         //   JOptionPane.showMessageDialog(null,"Invalid values");
       // }
            Payment_JPanel paymentjpanel=new Payment_JPanel(Display_JPanel,paymentcatalog);
            Display_JPanel.add("Payment_JPanel",paymentjpanel);
            CardLayout layout=(CardLayout) Display_JPanel.getLayout();
            layout.next(Display_JPanel);
    }//GEN-LAST:event_Next_JButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLine1_JLabel;
    private javax.swing.JTextField AddressLine1_JTextField;
    private javax.swing.JLabel AddressLine2_JLabel;
    private javax.swing.JTextField AddressLine2_JTextField;
    private javax.swing.JLabel Age_JLabel;
    private javax.swing.JTextField Age_JTextField;
    private javax.swing.JButton Back_JButton;
    private javax.swing.JLabel BookingForm_JLabel;
    private javax.swing.JLabel City_JLabel;
    private javax.swing.JTextField City_JTextField;
    private javax.swing.JLabel CustomerName_JLabel;
    private javax.swing.JTextField CustomerName_JTextField;
    private javax.swing.JLabel EmailID_JLabel;
    private javax.swing.JTextField EmailID_JTextField;
    private javax.swing.JButton Next_JButton;
    private javax.swing.JLabel PhoneNumber_JLabel;
    private javax.swing.JTextField PhoneNumber_JTextField;
    private javax.swing.JLabel SSN_JLabel;
    private javax.swing.JTextField SSN_JTextField;
    private javax.swing.JLabel Sex_JLabel;
    private javax.swing.JTextField Sex_JTextField;
    private javax.swing.JLabel Zipcode_JLabel;
    private javax.swing.JTextField Zipcode_JTextField;
    // End of variables declaration//GEN-END:variables
}
