/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MasterScheduleUserInterface;
import javax.swing.JOptionPane;
import Business.AirplaneCatalog;
import Business.Airplane;
import Business.Airliner;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rusha
 */
public class MasterScheduleView_JPanel extends javax.swing.JPanel {
private AirplaneCatalog airplanecatalog;
private JPanel Display_JPanel;
private Airplane airplane;
private Airliner airliner;
    /**
     * Creates new form MasterScheduleView_JPanel
     */
  
    public MasterScheduleView_JPanel(JPanel Display_JPanel,Airplane airplane , String air) {
        
         // this.airplanecatalog=airplanecatalog;
        
        initComponents();
        this.Display_JPanel=Display_JPanel;       
        this.airplane=airplane;
   
       // AirlinerName_JTextField.setText(airliner.getAirlinerName());
        //Airplane air=airplanecatalog.getAirplaneCatalog();
        PlaneName_JTextField.setText(airplane.getPlaneName());
        Price_JTextField.setText(String.valueOf(airplane.getPrice()));
        Seats_JTextField.setText(String.valueOf(airplane.getSeats()));
        ID_JTextField.setText(String.valueOf(airplane.getPlaneID()));
        Description_JTextField.setText(airplane.getDescription());
        From_JTextField.setText(airplane.getFrom());
        To_JTextField.setText(airplane.getTo());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewAirplane_JLabel = new javax.swing.JLabel();
        AirlinerName_JLabel = new javax.swing.JLabel();
        AirlinerName_JTextField = new javax.swing.JTextField();
        Price_JTextField = new javax.swing.JTextField();
        Price_JLabel = new javax.swing.JLabel();
        PlaneName_JTextField = new javax.swing.JTextField();
        PlaneName_JLabel = new javax.swing.JLabel();
        Description_JLabel = new javax.swing.JLabel();
        Description_JTextField = new javax.swing.JTextField();
        ID_JLabel = new javax.swing.JLabel();
        ID_JTextField = new javax.swing.JTextField();
        Seats_JLabel = new javax.swing.JLabel();
        Seats_JTextField = new javax.swing.JTextField();
        To_JLabel = new javax.swing.JLabel();
        From_JTextField = new javax.swing.JTextField();
        From_JLabel = new javax.swing.JLabel();
        To_JTextField = new javax.swing.JTextField();
        Back_JButton = new javax.swing.JButton();

        ViewAirplane_JLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ViewAirplane_JLabel.setText("View Airplane");

        AirlinerName_JLabel.setText("Airliner Name:");

        AirlinerName_JTextField.setEditable(false);
        AirlinerName_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlinerName_JTextFieldActionPerformed(evt);
            }
        });

        Price_JTextField.setEditable(false);
        Price_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price_JTextFieldActionPerformed(evt);
            }
        });

        Price_JLabel.setText("Price:");

        PlaneName_JTextField.setEditable(false);
        PlaneName_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaneName_JTextFieldActionPerformed(evt);
            }
        });

        PlaneName_JLabel.setText("Plane Name:");

        Description_JLabel.setText("Description:");

        Description_JTextField.setEditable(false);
        Description_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Description_JTextFieldActionPerformed(evt);
            }
        });

        ID_JLabel.setText("Plane ID:");

        ID_JTextField.setEditable(false);
        ID_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_JTextFieldActionPerformed(evt);
            }
        });

        Seats_JLabel.setText("Seats:");

        Seats_JTextField.setEditable(false);
        Seats_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seats_JTextFieldActionPerformed(evt);
            }
        });

        To_JLabel.setText("To");

        From_JTextField.setEditable(false);
        From_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                From_JTextFieldActionPerformed(evt);
            }
        });

        From_JLabel.setText("From");

        To_JTextField.setEditable(false);
        To_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                To_JTextFieldActionPerformed(evt);
            }
        });

        Back_JButton.setText("Back");
        Back_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(From_JLabel)
                            .addComponent(To_JLabel))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(To_JTextField)
                            .addComponent(From_JTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Description_JLabel)
                            .addComponent(ID_JLabel)
                            .addComponent(Seats_JLabel)
                            .addComponent(Price_JLabel)
                            .addComponent(PlaneName_JLabel)
                            .addComponent(Back_JButton)
                            .addComponent(AirlinerName_JLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlaneName_JTextField)
                            .addComponent(Seats_JTextField)
                            .addComponent(ID_JTextField)
                            .addComponent(Description_JTextField)
                            .addComponent(Price_JTextField)
                            .addComponent(ViewAirplane_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(AirlinerName_JTextField))))
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(ViewAirplane_JLabel)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlinerName_JLabel)
                    .addComponent(AirlinerName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaneName_JLabel)
                    .addComponent(PlaneName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price_JLabel)
                    .addComponent(Price_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seats_JLabel)
                    .addComponent(Seats_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_JLabel)
                    .addComponent(ID_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Description_JLabel)
                    .addComponent(Description_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(From_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(From_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(To_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(To_JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(Back_JButton)
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Back_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_JButtonActionPerformed
        // TODO add your handling code here:
        Display_JPanel.remove(this);
        CardLayout layout=(CardLayout)Display_JPanel.getLayout();
        layout.previous(Display_JPanel);

    }//GEN-LAST:event_Back_JButtonActionPerformed

    private void Price_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price_JTextFieldActionPerformed

    private void PlaneName_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaneName_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaneName_JTextFieldActionPerformed

    private void Description_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Description_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Description_JTextFieldActionPerformed

    private void ID_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_JTextFieldActionPerformed

    private void Seats_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seats_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Seats_JTextFieldActionPerformed

    private void From_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_From_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_From_JTextFieldActionPerformed

    private void To_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_To_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_To_JTextFieldActionPerformed

    private void AirlinerName_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlinerName_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirlinerName_JTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AirlinerName_JLabel;
    private javax.swing.JTextField AirlinerName_JTextField;
    private javax.swing.JButton Back_JButton;
    private javax.swing.JLabel Description_JLabel;
    private javax.swing.JTextField Description_JTextField;
    private javax.swing.JLabel From_JLabel;
    private javax.swing.JTextField From_JTextField;
    private javax.swing.JLabel ID_JLabel;
    private javax.swing.JTextField ID_JTextField;
    private javax.swing.JLabel PlaneName_JLabel;
    private javax.swing.JTextField PlaneName_JTextField;
    private javax.swing.JLabel Price_JLabel;
    private javax.swing.JTextField Price_JTextField;
    private javax.swing.JLabel Seats_JLabel;
    private javax.swing.JTextField Seats_JTextField;
    private javax.swing.JLabel To_JLabel;
    private javax.swing.JTextField To_JTextField;
    private javax.swing.JLabel ViewAirplane_JLabel;
    // End of variables declaration//GEN-END:variables
}
