/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MasterScheduleUserInterface;
import Business.CustomerBooking;
import Business.CustomerCatalog;
import Business.Payment;
import Business.PaymentCatalog;
import ManageAirplaneUserInterface.ManageViewAirplane_JPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author rusha
 */
public class PaymentViewJPanel extends javax.swing.JPanel {
private JPanel Display_JPanel;
private CustomerBooking customerbooking;
private Payment payment;
private CustomerCatalog customercatalog;
private PaymentCatalog paymentcatalog;
    /**
     * Creates new form PaymentViewJPanel
     */
    public PaymentViewJPanel(JPanel Display_JPanel,CustomerCatalog customercatalog) {
        initComponents();
        this.Display_JPanel=Display_JPanel;
        this.payment=payment;
        this.paymentcatalog=paymentcatalog;
        this.customerbooking=customerbooking;
        this.customercatalog=customercatalog;
        
        CustomerName_JTextField.setText(customerbooking.getCustomerName());
        Age_JTextField.setText(String.valueOf(customerbooking.getAge()));
        Sex_JTextField.setText(customerbooking.getSex());
        AddressLine1_JTextField.setText(customerbooking.getAddressLine1());
        AddressLine2_JTextField.setText(customerbooking.getAddressLine2());
        City_JTextField.setText(customerbooking.getCity());
        Zipcode_JTextField.setText(String.valueOf(customerbooking.getZipcode()));
        SSN_JTextField.setText(String.valueOf(customerbooking.getSSN()));
        EmailID_JTextField.setText(customerbooking.getEmailID());
        PhoneNumber_JTextField.setText(String.valueOf(customerbooking.getPhoneNumber()));
        
        NameOnCard_JTextField.setText(payment.getNameOnCard());
        CardNumber_JTextField.setText(String.valueOf(payment.getCardNumber()));
        CVV_JTextField.setText(String.valueOf(payment.getCVV()));
        GoodThrough_JTextField.setText(payment.getGoodThrough());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SSN_JLabel = new javax.swing.JLabel();
        Zipcode_JTextField = new javax.swing.JTextField();
        Sex_JLabel = new javax.swing.JLabel();
        SSN_JTextField = new javax.swing.JTextField();
        EmailID_JLabel = new javax.swing.JLabel();
        Sex_JTextField = new javax.swing.JTextField();
        AddressLine1_JTextField = new javax.swing.JTextField();
        AddressLine1_JLabel = new javax.swing.JLabel();
        Age_JTextField = new javax.swing.JTextField();
        Age_JLabel = new javax.swing.JLabel();
        CustomerName_JTextField = new javax.swing.JTextField();
        CustomerName_JLabel = new javax.swing.JLabel();
        Zipcode_JLabel = new javax.swing.JLabel();
        City_JLabel = new javax.swing.JLabel();
        City_JTextField = new javax.swing.JTextField();
        AddressLine2_JLabel = new javax.swing.JLabel();
        AddressLine2_JTextField = new javax.swing.JTextField();
        EmailID_JTextField = new javax.swing.JTextField();
        PhoneNumber_JLabel = new javax.swing.JLabel();
        PhoneNumber_JTextField = new javax.swing.JTextField();
        BookingForm_JLabel = new javax.swing.JLabel();
        NameOnCard_JLabel = new javax.swing.JLabel();
        NameOnCard_JTextField = new javax.swing.JTextField();
        CVV_JTextField = new javax.swing.JTextField();
        CVV_JLabel = new javax.swing.JLabel();
        CardNumber_JTextField = new javax.swing.JTextField();
        GoodThrough_JLabel1 = new javax.swing.JLabel();
        GoodThrough_JTextField = new javax.swing.JTextField();
        CardNumber_JLabel = new javax.swing.JLabel();
        PaymentDetails_JLabel = new javax.swing.JLabel();
        Update_JButton = new javax.swing.JButton();
        Save_JButton = new javax.swing.JButton();
        Back_JButton = new javax.swing.JButton();

        SSN_JLabel.setText("SSN");

        Zipcode_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zipcode_JTextFieldActionPerformed(evt);
            }
        });

        Sex_JLabel.setText("Sex");

        SSN_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSN_JTextFieldActionPerformed(evt);
            }
        });

        EmailID_JLabel.setText("Email ID");

        Sex_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sex_JTextFieldActionPerformed(evt);
            }
        });

        AddressLine1_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressLine1_JTextFieldActionPerformed(evt);
            }
        });

        AddressLine1_JLabel.setText("Address Line 1");

        Age_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_JTextFieldActionPerformed(evt);
            }
        });

        Age_JLabel.setText("Age");

        CustomerName_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerName_JTextFieldActionPerformed(evt);
            }
        });

        CustomerName_JLabel.setText("Customer Name:");

        Zipcode_JLabel.setText("Zipcode");

        City_JLabel.setText("City");

        City_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                City_JTextFieldActionPerformed(evt);
            }
        });

        AddressLine2_JLabel.setText("Address Line 2");

        AddressLine2_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressLine2_JTextFieldActionPerformed(evt);
            }
        });

        EmailID_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailID_JTextFieldActionPerformed(evt);
            }
        });

        PhoneNumber_JLabel.setText("Phone Number");

        PhoneNumber_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumber_JTextFieldActionPerformed(evt);
            }
        });

        BookingForm_JLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BookingForm_JLabel.setText("Booking Form");

        NameOnCard_JLabel.setText(" Name on Card");

        NameOnCard_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameOnCard_JTextFieldActionPerformed(evt);
            }
        });

        CVV_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVV_JTextFieldActionPerformed(evt);
            }
        });

        CVV_JLabel.setText("CVV");

        CardNumber_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNumber_JTextFieldActionPerformed(evt);
            }
        });

        GoodThrough_JLabel1.setText("Good Through");

        GoodThrough_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoodThrough_JTextFieldActionPerformed(evt);
            }
        });

        CardNumber_JLabel.setText("Card Number");

        PaymentDetails_JLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PaymentDetails_JLabel.setText("Payment Details");

        Update_JButton.setText("Update");
        Update_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_JButtonActionPerformed(evt);
            }
        });

        Save_JButton.setText("Save");
        Save_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_JButtonActionPerformed(evt);
            }
        });

        Back_JButton.setText("Back");
        Back_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PhoneNumber_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PhoneNumber_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EmailID_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmailID_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Sex_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sex_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SSN_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SSN_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Zipcode_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Zipcode_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(City_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(City_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddressLine2_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddressLine2_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddressLine1_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddressLine1_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Age_JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Age_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CustomerName_JLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookingForm_JLabel)
                            .addComponent(CustomerName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(CVV_JLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CVV_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(CardNumber_JLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CardNumber_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NameOnCard_JLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(NameOnCard_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(GoodThrough_JLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GoodThrough_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(PaymentDetails_JLabel))
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back_JButton)
                        .addGap(18, 18, 18)
                        .addComponent(Save_JButton)
                        .addGap(18, 18, 18)
                        .addComponent(Update_JButton)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingForm_JLabel)
                    .addComponent(PaymentDetails_JLabel))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerName_JLabel)
                            .addComponent(CustomerName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age_JLabel)
                            .addComponent(Age_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sex_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sex_JLabel))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressLine1_JLabel)
                            .addComponent(AddressLine1_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameOnCard_JLabel)
                            .addComponent(NameOnCard_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CardNumber_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CardNumber_JLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoodThrough_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GoodThrough_JLabel1))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CVV_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CVV_JLabel))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressLine2_JLabel)
                    .addComponent(AddressLine2_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(City_JLabel)
                    .addComponent(City_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zipcode_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Zipcode_JLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSN_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSN_JLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Save_JButton)
                            .addComponent(Update_JButton)
                            .addComponent(Back_JButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailID_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailID_JLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNumber_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumber_JLabel))))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Zipcode_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zipcode_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Zipcode_JTextFieldActionPerformed

    private void SSN_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSN_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSN_JTextFieldActionPerformed

    private void Sex_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sex_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sex_JTextFieldActionPerformed

    private void AddressLine1_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressLine1_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressLine1_JTextFieldActionPerformed

    private void Age_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_JTextFieldActionPerformed

    private void CustomerName_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerName_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerName_JTextFieldActionPerformed

    private void City_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_City_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_City_JTextFieldActionPerformed

    private void AddressLine2_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressLine2_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressLine2_JTextFieldActionPerformed

    private void EmailID_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailID_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailID_JTextFieldActionPerformed

    private void PhoneNumber_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumber_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumber_JTextFieldActionPerformed

    private void NameOnCard_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameOnCard_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameOnCard_JTextFieldActionPerformed

    private void CVV_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVV_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVV_JTextFieldActionPerformed

    private void CardNumber_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNumber_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNumber_JTextFieldActionPerformed

    private void GoodThrough_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoodThrough_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoodThrough_JTextFieldActionPerformed

    private void Update_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_JButtonActionPerformed
        // TODO add your handling code here:
        CustomerName_JTextField.setEditable(true);
        Age_JTextField.setEditable(true);
        Sex_JTextField.setEditable(true);
        AddressLine1_JTextField.setEditable(true);
        AddressLine2_JTextField.setEditable(true);
        City_JTextField.setEditable(true);
        Zipcode_JTextField.setEditable(true);
        SSN_JTextField.setEditable(true);
        EmailID_JTextField.setEditable(true);
        PhoneNumber_JTextField.setEditable(true);
        
        NameOnCard_JTextField.setEditable(true);
        CardNumber_JTextField.setEditable(true);
        GoodThrough_JTextField.setEditable(true);
        CVV_JTextField.setEditable(true);
        
        Save_JButton.setEnabled(true);
        Update_JButton.setEnabled(false);
    }//GEN-LAST:event_Update_JButtonActionPerformed

    private void Save_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_JButtonActionPerformed
        // TODO add your handling code here:

        CustomerName_JTextField.setEditable(false);
        Age_JTextField.setEditable(false);
        Sex_JTextField.setEditable(false);
        AddressLine1_JTextField.setEditable(false);
        AddressLine2_JTextField.setEditable(false);
        City_JTextField.setEditable(false);
        Zipcode_JTextField.setEditable(false);
        SSN_JTextField.setEditable(false);
        EmailID_JTextField.setEditable(false);
        PhoneNumber_JTextField.setEditable(false);
        
        NameOnCard_JTextField.setEditable(false);
        CardNumber_JTextField.setEditable(false);
        GoodThrough_JTextField.setEditable(false);
        CVV_JTextField.setEditable(false);
        
        Save_JButton.setEnabled(false);
        Update_JButton.setEnabled(true);

        try{
            
            customerbooking.setCustomerName(CustomerName_JTextField.getText());
            customerbooking.setAge(Integer.parseInt(Age_JTextField.getText()));
            customerbooking.setSex(Sex_JTextField.getText());
            customerbooking.setAddressLine1(AddressLine1_JTextField.getText());
            customerbooking.setAddressLine1(AddressLine2_JTextField.getText());
            customerbooking.setCity(City_JTextField.getText());
            customerbooking.setZipcode(Integer.parseInt(Zipcode_JTextField.getText()));
            customerbooking.setSSN(Integer.parseInt(SSN_JTextField.getText()));
            customerbooking.setEmailID(EmailID_JTextField.getText());
            customerbooking.setPhoneNumber(Integer.parseInt(PhoneNumber_JTextField.getText()));

            if(CustomerName_JTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please add all the Values");
            }
            else{
                JOptionPane.showMessageDialog(null, "Airliner Created Successfully");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Invalid values");
        }
    }//GEN-LAST:event_Save_JButtonActionPerformed

    private void Back_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_JButtonActionPerformed
        // TODO add your handling code here:
        Display_JPanel.remove(this);
        CardLayout cardLayout=(CardLayout)Display_JPanel.getLayout();
        cardLayout.previous(Display_JPanel);
        Component [] components=Display_JPanel.getComponents();
        for(Component c : components){
            if(c instanceof Payment_JPanel){
                Payment_JPanel panel=(Payment_JPanel)c;
                panel.refreshTable();
            }
        }
    }//GEN-LAST:event_Back_JButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLine1_JLabel;
    private javax.swing.JTextField AddressLine1_JTextField;
    private javax.swing.JLabel AddressLine2_JLabel;
    private javax.swing.JTextField AddressLine2_JTextField;
    private javax.swing.JLabel Age_JLabel;
    private javax.swing.JTextField Age_JTextField;
    private javax.swing.JButton Back_JButton;
    private javax.swing.JLabel BookingForm_JLabel;
    private javax.swing.JLabel CVV_JLabel;
    private javax.swing.JTextField CVV_JTextField;
    private javax.swing.JLabel CardNumber_JLabel;
    private javax.swing.JTextField CardNumber_JTextField;
    private javax.swing.JLabel City_JLabel;
    private javax.swing.JTextField City_JTextField;
    private javax.swing.JLabel CustomerName_JLabel;
    private javax.swing.JTextField CustomerName_JTextField;
    private javax.swing.JLabel EmailID_JLabel;
    private javax.swing.JTextField EmailID_JTextField;
    private javax.swing.JLabel GoodThrough_JLabel1;
    private javax.swing.JTextField GoodThrough_JTextField;
    private javax.swing.JLabel NameOnCard_JLabel;
    private javax.swing.JTextField NameOnCard_JTextField;
    private javax.swing.JLabel PaymentDetails_JLabel;
    private javax.swing.JLabel PhoneNumber_JLabel;
    private javax.swing.JTextField PhoneNumber_JTextField;
    private javax.swing.JLabel SSN_JLabel;
    private javax.swing.JTextField SSN_JTextField;
    private javax.swing.JButton Save_JButton;
    private javax.swing.JLabel Sex_JLabel;
    private javax.swing.JTextField Sex_JTextField;
    private javax.swing.JButton Update_JButton;
    private javax.swing.JLabel Zipcode_JLabel;
    private javax.swing.JTextField Zipcode_JTextField;
    // End of variables declaration//GEN-END:variables
}
