/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.MainClass;
import Business.Person;
import Business.Address;

/**
 *
 * @author rusha
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Address address;
    private Person person;
    private MainClass objMainClass;
    public MainJFrame() {
        initComponents();
        person =new Person();
        InitializePersonInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSplitPane = new javax.swing.JSplitPane();
        Control_JPanel = new javax.swing.JPanel();
        View_JButton = new javax.swing.JButton();
        Display_JPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        View_JButton.setText("View!");
        View_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Control_JPanelLayout = new javax.swing.GroupLayout(Control_JPanel);
        Control_JPanel.setLayout(Control_JPanelLayout);
        Control_JPanelLayout.setHorizontalGroup(
            Control_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Control_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(View_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        Control_JPanelLayout.setVerticalGroup(
            Control_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Control_JPanelLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(View_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        JSplitPane.setLeftComponent(Control_JPanel);

        javax.swing.GroupLayout Display_JPanelLayout = new javax.swing.GroupLayout(Display_JPanel);
        Display_JPanel.setLayout(Display_JPanelLayout);
        Display_JPanelLayout.setHorizontalGroup(
            Display_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        Display_JPanelLayout.setVerticalGroup(
            Display_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        JSplitPane.setRightComponent(Display_JPanel);

        getContentPane().add(JSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void View_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_JButtonActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewJPanel=new ViewJPanel(person);
        JSplitPane.setRightComponent(viewJPanel);
    }//GEN-LAST:event_View_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Control_JPanel;
    private javax.swing.JPanel Display_JPanel;
    private javax.swing.JSplitPane JSplitPane;
    private javax.swing.JButton View_JButton;
    // End of variables declaration//GEN-END:variables

    private void InitializePersonInfo() {
    person.setFirstName("Rushabh");
    person.setLastName("Nisher");
    person.setDateOfBirth("1995/11/21");
    person.setSSN("123-456-7899");
    
    Address WorkAddress=new Address();
    WorkAddress.setStreetLine1("360, Huntington Ave");
    WorkAddress.setStreetLine2("");
    WorkAddress.setCity("Boston");
    WorkAddress.setState("MA");
    WorkAddress.setZipcode("02115");
    WorkAddress.setCountry("United States");
    person.setWorkAddress(WorkAddress);
    
    Address LocalAddress=new Address();
    LocalAddress.setStreetLine1("55 Burbank Street");
    LocalAddress.setStreetLine2("Apartment Number 15");
    LocalAddress.setCity("Boston");
    LocalAddress.setState("MA");
    LocalAddress.setZipcode("02115");
    LocalAddress.setCountry("United States");
    person.setLocalAddress(LocalAddress);
    
    Address HomeAddress=new Address();
    HomeAddress.setStreetLine1("350/101 A, Balaram Bhuvan, Balaram Street,");
    HomeAddress.setStreetLine2("M.S.ALi Road, Grant Road (East)");
    HomeAddress.setCity("Mumbai");
    HomeAddress.setState("Maharashtra");
    HomeAddress.setZipcode("400007");
    HomeAddress.setCountry("India");
    person.setHomeAddress(HomeAddress);
    }
}
