/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Hospital.VitalSign_History;
import Hospital.VitalSigns;
import javax.swing.JOptionPane;
/**
 *
 * @author rusha
 */

public class Create_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form Create_JPanel
     */
private VitalSign_History vitalsign_history;
public Create_JPanel(VitalSign_History vitalsign_history) {
    initComponents();
    this.vitalsign_history=vitalsign_history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateVitalSigns_JLabel = new javax.swing.JLabel();
        Temperature_JLabel = new javax.swing.JLabel();
        Temperature_JTextField = new javax.swing.JTextField();
        BloodPressure_JLabel = new javax.swing.JLabel();
        BloodPressure_JTextField = new javax.swing.JTextField();
        Pulse_JLabel = new javax.swing.JLabel();
        Pulse_JTextField = new javax.swing.JTextField();
        Date_JLabel = new javax.swing.JLabel();
        Date_JTextField = new javax.swing.JTextField();
        Create_JButton = new javax.swing.JButton();
        InvalidTemperature_JLabel = new javax.swing.JLabel();
        InvalidPulse_JLabel = new javax.swing.JLabel();
        InvalidBloodPressure_JLabel = new javax.swing.JLabel();

        CreateVitalSigns_JLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CreateVitalSigns_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateVitalSigns_JLabel.setText("Create Vital Signs");

        Temperature_JLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Temperature_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Temperature_JLabel.setText("Temperature:");

        Temperature_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Temperature_JTextFieldActionPerformed(evt);
            }
        });
        Temperature_JTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Temperature_JTextFieldKeyTyped(evt);
            }
        });

        BloodPressure_JLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BloodPressure_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BloodPressure_JLabel.setText("Blood Pressure:");

        BloodPressure_JTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BloodPressure_JTextFieldKeyTyped(evt);
            }
        });

        Pulse_JLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Pulse_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pulse_JLabel.setText("Pulse:");

        Pulse_JTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Pulse_JTextFieldKeyTyped(evt);
            }
        });

        Date_JLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Date_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Date_JLabel.setText("Date:");

        Create_JButton.setText("Create!");
        Create_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_JButtonActionPerformed(evt);
            }
        });

        InvalidTemperature_JLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InvalidTemperature_JLabel.setForeground(new java.awt.Color(51, 255, 0));

        InvalidPulse_JLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InvalidPulse_JLabel.setForeground(new java.awt.Color(51, 255, 0));

        InvalidBloodPressure_JLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InvalidBloodPressure_JLabel.setForeground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateVitalSigns_JLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BloodPressure_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BloodPressure_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Temperature_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Temperature_JTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pulse_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Pulse_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Date_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Create_JButton)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(Date_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InvalidPulse_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvalidTemperature_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvalidBloodPressure_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateVitalSigns_JLabel)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Temperature_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Temperature_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvalidTemperature_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BloodPressure_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BloodPressure_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Pulse_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Pulse_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(InvalidPulse_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Date_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(Create_JButton))
                    .addComponent(InvalidBloodPressure_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Create_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_JButtonActionPerformed
        // TODO add your handling code here:
        try{
        float Temperature=Float.parseFloat(Temperature_JTextField.getText());
        float BloodPressure=Float.parseFloat(BloodPressure_JTextField.getText());
        int Pulse=Integer.parseInt(Pulse_JTextField.getText());
        String Date=Date_JTextField.getText();
        
        
        VitalSigns vitalsign=vitalsign_history.addVitalSigns();
        
        vitalsign.setTemperature(Temperature);
        vitalsign.setBloodPressure(BloodPressure);
        vitalsign.setPulse(Pulse);
        vitalsign.setDate(Date);
        
        JOptionPane.showMessageDialog(null, "Vital Signs are Saved Sucessfully!");
        
        Temperature_JTextField.setText("");
        BloodPressure_JTextField.setText("");
        Pulse_JTextField.setText("");
        Date_JTextField.setText("");
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"Invalid values");
        }
    }//GEN-LAST:event_Create_JButtonActionPerformed

    private void Temperature_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Temperature_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Temperature_JTextFieldActionPerformed

    private void Temperature_JTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Temperature_JTextFieldKeyTyped
        // TODO add your handling code here:
        try{
        float Temperature=Float.parseFloat(Temperature_JTextField.getText());
        InvalidTemperature_JLabel.setText("");
        }
        catch(Exception e){
        InvalidTemperature_JLabel.setText("Invalid Input");
        }
    }//GEN-LAST:event_Temperature_JTextFieldKeyTyped

    private void BloodPressure_JTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BloodPressure_JTextFieldKeyTyped
        // TODO add your handling code here:
          try{
        float BloodPressure=Float.parseFloat(BloodPressure_JTextField.getText());      
        InvalidBloodPressure_JLabel.setText("");
        }
        catch(Exception e){
        InvalidBloodPressure_JLabel.setText("Invalid Input");
        }
    }//GEN-LAST:event_BloodPressure_JTextFieldKeyTyped

    private void Pulse_JTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pulse_JTextFieldKeyTyped
        // TODO add your handling code here:
         try{        
        int Pulse=Integer.parseInt(Pulse_JTextField.getText());
        InvalidPulse_JLabel.setText("");
        }
        catch(Exception e){
        InvalidPulse_JLabel.setText("Invalid Input");
        }
        
    }//GEN-LAST:event_Pulse_JTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodPressure_JLabel;
    private javax.swing.JTextField BloodPressure_JTextField;
    private javax.swing.JLabel CreateVitalSigns_JLabel;
    private javax.swing.JButton Create_JButton;
    private javax.swing.JLabel Date_JLabel;
    private javax.swing.JTextField Date_JTextField;
    private javax.swing.JLabel InvalidBloodPressure_JLabel;
    private javax.swing.JLabel InvalidPulse_JLabel;
    private javax.swing.JLabel InvalidTemperature_JLabel;
    private javax.swing.JLabel Pulse_JLabel;
    private javax.swing.JTextField Pulse_JTextField;
    private javax.swing.JLabel Temperature_JLabel;
    private javax.swing.JTextField Temperature_JTextField;
    // End of variables declaration//GEN-END:variables
}
