/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Hospital.VitalSign_History;
import Hospital.VitalSigns;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author rusha
 */
public class Abnormal_JPanel extends javax.swing.JPanel {
double MaxPulse,MinPulse;
    /**
     * Creates new form Abnormal_JPanel
     */
    private VitalSign_History vitalsign_history;
    public Abnormal_JPanel(VitalSign_History vitalsign_history, double MaxPulse, double MinPulse) {
        initComponents();
        this.vitalsign_history=vitalsign_history;
        this.MaxPulse=MaxPulse;
        this.MinPulse=MinPulse;
        PopulateTable();
    }
    public void PopulateTable(){
        DefaultTableModel defaulttablemodel = (DefaultTableModel)JTable.getModel();
        defaulttablemodel.setRowCount(0);
        
        for(VitalSigns vitalsigns : vitalsign_history.getAbnormalList(MaxPulse, MinPulse)){
                        
            Object row[]=new Object[2]; 
            row[0]=vitalsigns;      
            row[1]=vitalsigns.getPulse();
            defaulttablemodel.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Date_JTextField = new javax.swing.JTextField();
        Date_JLabel = new javax.swing.JLabel();
        Pulse_JTextField = new javax.swing.JTextField();
        Table_JScrollPane = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        Temperature_JLabel = new javax.swing.JLabel();
        Temperature_JTextField = new javax.swing.JTextField();
        ViewDetails_JButton = new javax.swing.JButton();
        Delete_JButton = new javax.swing.JButton();
        Pulse_JLabel = new javax.swing.JLabel();
        BloodPressure_JLabel = new javax.swing.JLabel();
        BloodPressure_JTextField = new javax.swing.JTextField();
        ViewVitalSigns_JLabel = new javax.swing.JLabel();

        Date_JTextField.setEditable(false);
        Date_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        Date_JLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Date_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Date_JLabel.setText("Date:");

        Pulse_JTextField.setEditable(false);
        Pulse_JTextField.setBackground(new java.awt.Color(255, 255, 255));
        Pulse_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pulse_JTextFieldActionPerformed(evt);
            }
        });

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Pulse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_JScrollPane.setViewportView(JTable);

        Temperature_JLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Temperature_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Temperature_JLabel.setText("Temperature:");

        Temperature_JTextField.setEditable(false);
        Temperature_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        ViewDetails_JButton.setText("View Details");
        ViewDetails_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetails_JButtonActionPerformed(evt);
            }
        });

        Delete_JButton.setText("Delete");
        Delete_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_JButtonActionPerformed(evt);
            }
        });

        Pulse_JLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Pulse_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pulse_JLabel.setText("Pulse:");

        BloodPressure_JLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BloodPressure_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BloodPressure_JLabel.setText("Blood Pressure:");

        BloodPressure_JTextField.setEditable(false);
        BloodPressure_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        ViewVitalSigns_JLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ViewVitalSigns_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewVitalSigns_JLabel.setText("Abnormal Vital Signs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Date_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Date_JTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Pulse_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Pulse_JTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BloodPressure_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BloodPressure_JTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Temperature_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Temperature_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ViewVitalSigns_JLabel)
                    .addComponent(Table_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewDetails_JButton)
                        .addGap(18, 18, 18)
                        .addComponent(Delete_JButton)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewVitalSigns_JLabel)
                .addGap(21, 21, 21)
                .addComponent(Table_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete_JButton)
                    .addComponent(ViewDetails_JButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Temperature_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Temperature_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodPressure_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BloodPressure_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pulse_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pulse_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Pulse_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pulse_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pulse_JTextFieldActionPerformed

    private void ViewDetails_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetails_JButtonActionPerformed
        // TODO add your handling code here:
        int SelectedRow=JTable.getSelectedRow();

        if(SelectedRow>=0){
            VitalSigns vitalsigns=(VitalSigns)JTable.getValueAt(SelectedRow, 0);
            Temperature_JTextField.setText(String.valueOf(vitalsigns.getTemperature()));
            BloodPressure_JTextField.setText(String.valueOf(vitalsigns.getBloodPressure()));
            Pulse_JTextField.setText(String.valueOf(vitalsigns.getPulse()));
            Date_JTextField.setText(vitalsigns.getDate());
        }
        else{
            JOptionPane.showMessageDialog(null,"Please Select a Row!");
        }
    }//GEN-LAST:event_ViewDetails_JButtonActionPerformed

    private void Delete_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_JButtonActionPerformed
        // TODO add your handling code here:
        int SelectedRow=JTable.getSelectedRow();

        if(SelectedRow>=0){
            VitalSigns vitalsigns=(VitalSigns)JTable.getValueAt(SelectedRow, 0);
            vitalsign_history.deleteVitalSigns(vitalsigns);
            JOptionPane.showMessageDialog(null,"Selected Row is deleted Sucessfully!");
            PopulateTable();
            Temperature_JTextField.setText("");
            BloodPressure_JTextField.setText("");
            Pulse_JTextField.setText("");
            Date_JTextField.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null,"Please Select a Row!");
        }
    }//GEN-LAST:event_Delete_JButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodPressure_JLabel;
    private javax.swing.JTextField BloodPressure_JTextField;
    private javax.swing.JLabel Date_JLabel;
    private javax.swing.JTextField Date_JTextField;
    private javax.swing.JButton Delete_JButton;
    private javax.swing.JTable JTable;
    private javax.swing.JLabel Pulse_JLabel;
    private javax.swing.JTextField Pulse_JTextField;
    private javax.swing.JScrollPane Table_JScrollPane;
    private javax.swing.JLabel Temperature_JLabel;
    private javax.swing.JTextField Temperature_JTextField;
    private javax.swing.JButton ViewDetails_JButton;
    private javax.swing.JLabel ViewVitalSigns_JLabel;
    // End of variables declaration//GEN-END:variables
}
