/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Hospital.VitalSign_History;

/**
 *
 * @author rusha
 */
public class Main_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main_JFrame
     */
    private VitalSign_History vitalsign_history;
    public Main_JFrame() {
        initComponents();
        vitalsign_history=new VitalSign_History();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSplitPane = new javax.swing.JSplitPane();
        Control_JPanel = new javax.swing.JPanel();
        Create_JButton = new javax.swing.JButton();
        View_JButton = new javax.swing.JButton();
        VitalSigns_JLabel = new javax.swing.JLabel();
        MaxPulse_JLabel = new javax.swing.JLabel();
        MaxPulse_JTextField = new javax.swing.JTextField();
        MinPulse_JLabel = new javax.swing.JLabel();
        MinPulse_JTextField = new javax.swing.JTextField();
        Abnormal_JButton = new javax.swing.JButton();
        Display_JPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Create_JButton.setText("Create!");
        Create_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_JButtonActionPerformed(evt);
            }
        });

        View_JButton.setText("View!");
        View_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_JButtonActionPerformed(evt);
            }
        });

        VitalSigns_JLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VitalSigns_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VitalSigns_JLabel.setText("Vital Signs");

        MaxPulse_JLabel.setText("Max Pulse");

        MinPulse_JLabel.setText("Min Pulse");

        Abnormal_JButton.setText("Abnormal");
        Abnormal_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abnormal_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Control_JPanelLayout = new javax.swing.GroupLayout(Control_JPanel);
        Control_JPanel.setLayout(Control_JPanelLayout);
        Control_JPanelLayout.setHorizontalGroup(
            Control_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Control_JPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(Control_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Control_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(VitalSigns_JLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Abnormal_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(View_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Create_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MaxPulse_JLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Control_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MaxPulse_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Control_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MinPulse_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MinPulse_JLabel))))
                .addContainerGap())
        );
        Control_JPanelLayout.setVerticalGroup(
            Control_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Control_JPanelLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(VitalSigns_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Create_JButton)
                .addGap(38, 38, 38)
                .addComponent(View_JButton)
                .addGap(30, 30, 30)
                .addComponent(MaxPulse_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MaxPulse_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MinPulse_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MinPulse_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(Abnormal_JButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        JSplitPane.setLeftComponent(Control_JPanel);

        javax.swing.GroupLayout Display_JPanelLayout = new javax.swing.GroupLayout(Display_JPanel);
        Display_JPanel.setLayout(Display_JPanelLayout);
        Display_JPanelLayout.setHorizontalGroup(
            Display_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        Display_JPanelLayout.setVerticalGroup(
            Display_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        JSplitPane.setRightComponent(Display_JPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void View_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_JButtonActionPerformed
        // TODO add your handling code here:
        View_JPanel view_jpanel=new View_JPanel(vitalsign_history);
        JSplitPane.setRightComponent(view_jpanel);
    }//GEN-LAST:event_View_JButtonActionPerformed

    private void Create_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_JButtonActionPerformed
        // TODO add your handling code here:
        Create_JPanel create_jpanel=new Create_JPanel(vitalsign_history);
        JSplitPane.setRightComponent(create_jpanel);
    }//GEN-LAST:event_Create_JButtonActionPerformed

    private void Abnormal_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abnormal_JButtonActionPerformed
        // TODO add your handling code here:
        String MaxPulseString=MaxPulse_JTextField.getText();
        String MinPulseString=MinPulse_JTextField.getText();
        double MaxPulse=MaxPulseString.equals("")? Double.MAX_VALUE : Double.parseDouble(MaxPulseString);
        double MinPulse=MinPulseString.equals("")? Double.MIN_VALUE : Double.parseDouble(MinPulseString);
        Abnormal_JPanel abnormal_jpanel=new Abnormal_JPanel(vitalsign_history, MaxPulse, MinPulse);
        JSplitPane.setRightComponent(abnormal_jpanel);
    }//GEN-LAST:event_Abnormal_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abnormal_JButton;
    private javax.swing.JPanel Control_JPanel;
    private javax.swing.JButton Create_JButton;
    private javax.swing.JPanel Display_JPanel;
    private javax.swing.JSplitPane JSplitPane;
    private javax.swing.JLabel MaxPulse_JLabel;
    private javax.swing.JTextField MaxPulse_JTextField;
    private javax.swing.JLabel MinPulse_JLabel;
    private javax.swing.JTextField MinPulse_JTextField;
    private javax.swing.JButton View_JButton;
    private javax.swing.JLabel VitalSigns_JLabel;
    // End of variables declaration//GEN-END:variables
}
