/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Profile.Address;
import Profile.Bank;
import Profile.Demographic;
import Profile.DriversLicense;
import Profile.MedicalRecord;
import Profile.Person;
//import java.awt.Component;
/**
 *
 * @author rusha
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Demographic demographic;
    private Address address;
    private Bank bank;
    private DriversLicense driverslicense;
    private MedicalRecord medicalrecord;
    private Person person;
    public MainJFrame() {
        initComponents();
        person=new Person();
    //    demographic=new Demographic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSplitPane = new javax.swing.JSplitPane();
        ControlJPanel = new javax.swing.JPanel();
        View_JButton = new javax.swing.JButton();
        Create_JButton = new javax.swing.JButton();
        DisplayJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(216, 240, 232));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JSplitPane.setDividerLocation(175);
        JSplitPane.setDividerSize(10);

        ControlJPanel.setBackground(new java.awt.Color(186, 240, 232));
        ControlJPanel.setPreferredSize(new java.awt.Dimension(180, 670));

        View_JButton.setBackground(new java.awt.Color(207, 235, 235));
        View_JButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        View_JButton.setText("View!");
        View_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_JButtonActionPerformed(evt);
            }
        });

        Create_JButton.setBackground(new java.awt.Color(207, 235, 235));
        Create_JButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Create_JButton.setText("Create!");
        Create_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlJPanelLayout = new javax.swing.GroupLayout(ControlJPanel);
        ControlJPanel.setLayout(ControlJPanelLayout);
        ControlJPanelLayout.setHorizontalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(View_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Create_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ControlJPanelLayout.setVerticalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(Create_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(View_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        JSplitPane.setLeftComponent(ControlJPanel);

        DisplayJPanel.setBackground(new java.awt.Color(207, 235, 235));
        DisplayJPanel.setPreferredSize(new java.awt.Dimension(670, 670));

        javax.swing.GroupLayout DisplayJPanelLayout = new javax.swing.GroupLayout(DisplayJPanel);
        DisplayJPanel.setLayout(DisplayJPanelLayout);
        DisplayJPanelLayout.setHorizontalGroup(
            DisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        DisplayJPanelLayout.setVerticalGroup(
            DisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );

        JSplitPane.setRightComponent(DisplayJPanel);

        getContentPane().add(JSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void View_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_JButtonActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewJPanel=new ViewJPanel(person);
        JSplitPane.setRightComponent(viewJPanel);
        /**ViewJPanel viewJPaneld=new ViewJPanel(demographic);
        JSplitPane.setRightComponent(viewJPaneld);
        ViewJPanel viewJPanela=new ViewJPanel(address);
        JSplitPane.setRightComponent(viewJPanela);
        ViewJPanel viewJPanelb=new ViewJPanel(bank);
        JSplitPane.setRightComponent(viewJPanelb);
        ViewJPanel viewJPanell=new ViewJPanel(driverslicense);
        JSplitPane.setRightComponent(viewJPanell);
        ViewJPanel viewJPanelm=new ViewJPanel(medicalrecord);
        JSplitPane.setRightComponent(viewJPanelm);*/
    }//GEN-LAST:event_View_JButtonActionPerformed

    private void Create_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_JButtonActionPerformed
        // TODO add your handling code here:
        CreateJPanel createJPanel=new CreateJPanel(person);
        JSplitPane.setRightComponent(createJPanel);
    }//GEN-LAST:event_Create_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlJPanel;
    private javax.swing.JButton Create_JButton;
    private javax.swing.JPanel DisplayJPanel;
    private javax.swing.JSplitPane JSplitPane;
    private javax.swing.JButton View_JButton;
    // End of variables declaration//GEN-END:variables
}
