/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.MainClass;
import Business.Person;

/**
 *
 * @author rusha
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    //private MainClass main;
    private Person objPerson;
    public ViewJPanel(Person person) {
        initComponents();
        this.objPerson = person;
        displayMain(objPerson);
    }
        private void displayMain(Person person)
    {

        //Person
        String mainFirstName=person.getFirstName();
        FirstName_JTextField.setText(mainFirstName);
        String mainLastName=person.getLastName();
        LastName_JTextField.setText(mainLastName);
        String mainDateOfBirth=person.getDateOfBirth();
        DateOfBirth_JTextField.setText(mainDateOfBirth);
        String mainSSN=person.getSSN();
        SSN_JTextField.setText(mainSSN);

        //Work Address
        String mainWorkStreetLine1=person.getWorkAddress().getStreetLine1();
        WorkStreetLine1_JTextField.setText(mainWorkStreetLine1);
        String mainWorkStreetLine2=person.getWorkAddress().getStreetLine2();
        WorkStreetLine2_JTextField.setText(mainWorkStreetLine2);
        String mainWorkCity=person.getWorkAddress().getCity();
        WorkCity_JTextField.setText(mainWorkCity);
        String mainWorkState=person.getWorkAddress().getState();
        WorkState_JTextField.setText(mainWorkState);
        String mainWorkZipcode=person.getWorkAddress().getZipcode();
        WorkZipcode_JTextField.setText(mainWorkZipcode);
        String mainWorkCountry=person.getWorkAddress().getCountry();
        WorkCountry_JTextField.setText(mainWorkCountry);

        
        //Local Address
        String mainLocalStreetLine1=person.getLocalAddress().getStreetLine1();
        LocalStreetLine1_JTextField.setText(mainLocalStreetLine1);
        String mainLocalStreetLine2=person.getLocalAddress().getStreetLine2();
        LocalStreetLine2_JTextField.setText(mainLocalStreetLine2);
        String mainLocalCity=person.getLocalAddress().getCity();
        LocalCity_JTextField.setText(mainLocalCity);
        String mainLocalState=person.getLocalAddress().getState();
        LocalState_JTextField.setText(mainLocalState);
        String mainLocalZipcode=person.getLocalAddress().getZipcode();
        LocalZipcode_JTextField.setText(mainLocalZipcode);
        String mainLocalCountry=person.getLocalAddress().getCountry();
        LocalCountry_JTextField.setText(mainLocalCountry);        
        
        
        //Home Address
        String mainHomeStreetLine1=person.getHomeAddress().getStreetLine1();
        HomeStreetLine1_JTextField.setText(mainHomeStreetLine1);
        String mainHomeStreetLine2=person.getHomeAddress().getStreetLine2();
        HomeStreetLine2_JTextField.setText(mainHomeStreetLine2);
        String mainHomeCity=person.getHomeAddress().getCity();
        HomeCity_JTextField.setText(mainHomeCity);
        String mainHomeState=person.getHomeAddress().getState();
        HomeState_JTextField.setText(mainHomeState);
        String mainHomeZipcode=person.getHomeAddress().getZipcode();
        HomeZipcode_JTextField.setText(mainHomeZipcode);
        String mainHomeCountry=person.getHomeAddress().getCountry();
        HomeCountry_JTextField.setText(mainHomeCountry);                
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstName_JTextField = new javax.swing.JTextField();
        LastName_JTextField = new javax.swing.JTextField();
        DateOfBirth_JTextField = new javax.swing.JTextField();
        SSN_JTextField = new javax.swing.JTextField();
        WorkStreetLine1_JTextField = new javax.swing.JTextField();
        WorkStreetLine2_JTextField = new javax.swing.JTextField();
        WorkCity_JTextField = new javax.swing.JTextField();
        WorkState_JTextField = new javax.swing.JTextField();
        WorkZipcode_JTextField = new javax.swing.JTextField();
        WorkCountry_JTextField = new javax.swing.JTextField();
        LocalStreetLine1_JTextField = new javax.swing.JTextField();
        LocalStreetLine2_JTextField = new javax.swing.JTextField();
        LocalCity_JTextField = new javax.swing.JTextField();
        LocalState_JTextField = new javax.swing.JTextField();
        LocalZipcode_JTextField = new javax.swing.JTextField();
        LocalCountry_JTextField = new javax.swing.JTextField();
        HomeStreetLine1_JTextField = new javax.swing.JTextField();
        HomeStreetLine2_JTextField = new javax.swing.JTextField();
        HomeCity_JTextField = new javax.swing.JTextField();
        HomeState_JTextField = new javax.swing.JTextField();
        HomeZipcode_JTextField = new javax.swing.JTextField();
        HomeCountry_JTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        FirstName_JTextField.setEditable(false);
        FirstName_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        LastName_JTextField.setEditable(false);
        LastName_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        DateOfBirth_JTextField.setEditable(false);
        DateOfBirth_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        SSN_JTextField.setEditable(false);
        SSN_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        WorkStreetLine1_JTextField.setEditable(false);
        WorkStreetLine1_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        WorkStreetLine2_JTextField.setEditable(false);
        WorkStreetLine2_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        WorkCity_JTextField.setEditable(false);
        WorkCity_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        WorkState_JTextField.setEditable(false);
        WorkState_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        WorkZipcode_JTextField.setEditable(false);
        WorkZipcode_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        WorkCountry_JTextField.setEditable(false);
        WorkCountry_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        LocalStreetLine1_JTextField.setEditable(false);
        LocalStreetLine1_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        LocalStreetLine2_JTextField.setEditable(false);
        LocalStreetLine2_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        LocalCity_JTextField.setEditable(false);
        LocalCity_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        LocalState_JTextField.setEditable(false);
        LocalState_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        LocalZipcode_JTextField.setEditable(false);
        LocalZipcode_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        LocalCountry_JTextField.setEditable(false);
        LocalCountry_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        HomeStreetLine1_JTextField.setEditable(false);
        HomeStreetLine1_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        HomeStreetLine2_JTextField.setEditable(false);
        HomeStreetLine2_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        HomeCity_JTextField.setEditable(false);
        HomeCity_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        HomeState_JTextField.setEditable(false);
        HomeState_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        HomeZipcode_JTextField.setEditable(false);
        HomeZipcode_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        HomeCountry_JTextField.setEditable(false);
        HomeCountry_JTextField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Last Name:");

        jLabel2.setText("First Name:");

        jLabel3.setText("Date Of Birth:");

        jLabel4.setText("SSN:");

        jLabel5.setText("Street Line 1:");

        jLabel6.setText("Street Line 2:");

        jLabel7.setText("City:");

        jLabel8.setText("State:");

        jLabel9.setText("Zipcode:");

        jLabel10.setText("Country:");

        jLabel11.setText("Street Line 1:");

        jLabel12.setText("Street Line 2:");

        jLabel13.setText("City:");

        jLabel14.setText("State:");

        jLabel15.setText("Zipcode:");

        jLabel16.setText("Country:");

        jLabel17.setText("Street Line 1:");

        jLabel18.setText("Street Line 2:");

        jLabel19.setText("City:");

        jLabel20.setText("State:");

        jLabel21.setText("Zipcode:");

        jLabel22.setText("Country:");

        jLabel23.setText("Home Address");

        jLabel24.setText("Local Address:");

        jLabel25.setText("Work Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateOfBirth_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SSN_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WorkCountry_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WorkStreetLine2_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WorkStreetLine1_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WorkCity_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WorkState_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WorkZipcode_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel14)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12))))
                            .addComponent(jLabel25))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LocalStreetLine2_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LocalStreetLine1_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LocalCity_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LocalState_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LocalZipcode_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LocalCountry_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56)
                                    .addComponent(jLabel22)))
                            .addComponent(jLabel24))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomeStreetLine1_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeStreetLine2_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeCity_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeState_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeZipcode_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeCountry_JTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateOfBirth_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSN_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WorkStreetLine1_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(LocalStreetLine1_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeStreetLine1_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(WorkStreetLine2_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LocalStreetLine2_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HomeStreetLine2_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(WorkCity_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LocalCity_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HomeCity_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(WorkState_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addComponent(LocalState_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(HomeState_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(WorkZipcode_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LocalZipcode_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HomeZipcode_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(WorkCountry_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LocalCountry_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HomeCountry_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateOfBirth_JTextField;
    private javax.swing.JTextField FirstName_JTextField;
    private javax.swing.JTextField HomeCity_JTextField;
    private javax.swing.JTextField HomeCountry_JTextField;
    private javax.swing.JTextField HomeState_JTextField;
    private javax.swing.JTextField HomeStreetLine1_JTextField;
    private javax.swing.JTextField HomeStreetLine2_JTextField;
    private javax.swing.JTextField HomeZipcode_JTextField;
    private javax.swing.JTextField LastName_JTextField;
    private javax.swing.JTextField LocalCity_JTextField;
    private javax.swing.JTextField LocalCountry_JTextField;
    private javax.swing.JTextField LocalState_JTextField;
    private javax.swing.JTextField LocalStreetLine1_JTextField;
    private javax.swing.JTextField LocalStreetLine2_JTextField;
    private javax.swing.JTextField LocalZipcode_JTextField;
    private javax.swing.JTextField SSN_JTextField;
    private javax.swing.JTextField WorkCity_JTextField;
    private javax.swing.JTextField WorkCountry_JTextField;
    private javax.swing.JTextField WorkState_JTextField;
    private javax.swing.JTextField WorkStreetLine1_JTextField;
    private javax.swing.JTextField WorkStreetLine2_JTextField;
    private javax.swing.JTextField WorkZipcode_JTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
