/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageAirplaneUserInterface;
import Business.Airliner;
import Business.AirlinerCatalog;
import Business.Airplane;
import ManageAirplaneUserInterface.ManageViewAirplane_JPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author rusha
 */
public class AirlinerLogin_JPanel extends javax.swing.JPanel {
private JPanel Display_JPanel;
private AirlinerCatalog airlinercatalog;
    /**
     * Creates new form AirlinerLogin_JPanel
     */
    public AirlinerLogin_JPanel(JPanel Display_JPanel,AirlinerCatalog airlinercatalog) {
        initComponents();
        this.airlinercatalog=airlinercatalog;
        this.Display_JPanel=Display_JPanel;
        Airliner_JComboBox.removeAllItems();
        for(Airliner airliner : airlinercatalog.getAirlinerCatalog()){
        Airliner_JComboBox.addItem(airliner);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AirlinerLogin_JLabel = new javax.swing.JLabel();
        AirlinerName_JLabel = new javax.swing.JLabel();
        Airliner_JComboBox = new javax.swing.JComboBox();
        Go_JButton = new javax.swing.JButton();

        AirlinerLogin_JLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AirlinerLogin_JLabel.setText("Airliner Login");

        AirlinerName_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AirlinerName_JLabel.setText("Airlner Name");

        Airliner_JComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Airliner_JComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Airliner_JComboBoxActionPerformed(evt);
            }
        });

        Go_JButton.setText("GO>>");
        Go_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(AirlinerLogin_JLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(AirlinerName_JLabel)
                            .addGap(13, 13, 13)
                            .addComponent(Airliner_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(Go_JButton)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addComponent(AirlinerLogin_JLabel)
                    .addGap(51, 51, 51)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AirlinerName_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Airliner_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Go_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 157, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Go_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go_JButtonActionPerformed
        // TODO add your handling code here:
       Airliner airliner = (Airliner)Airliner_JComboBox.getSelectedItem();
       ManageAirplane_JPanel manageairplane = new ManageAirplane_JPanel(Display_JPanel, airliner);
       Display_JPanel.add("ManageAirlinerJPanel",manageairplane);
       CardLayout layout = (CardLayout)Display_JPanel.getLayout();
       layout.next(Display_JPanel);
    }//GEN-LAST:event_Go_JButtonActionPerformed

    private void Airliner_JComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Airliner_JComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Airliner_JComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AirlinerLogin_JLabel;
    private javax.swing.JLabel AirlinerName_JLabel;
    private javax.swing.JComboBox Airliner_JComboBox;
    private javax.swing.JButton Go_JButton;
    // End of variables declaration//GEN-END:variables
}
