/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageAirplaneUserInterface;

import Business.Airliner;
import Business.AirplaneCatalog;
import Business.Airplane;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author rusha
 */
public class CreateAirplane_JPanel extends javax.swing.JPanel {
private AirplaneCatalog airplanecatalog;
private Airplane airplane;
private Airliner airliner;
private JPanel Display_JPanel;
    /**
     * Creates new form CreateAirplane_JPanel
     */
    public CreateAirplane_JPanel(JPanel Display_JPanel,Airliner airliner) {
        initComponents();
        this.airplanecatalog=airplanecatalog;
        this.Display_JPanel=Display_JPanel;
        this.airplane=airplane;
        this.airliner=airliner;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateAirplane_JLabel = new javax.swing.JLabel();
        PlaneName_JLabel = new javax.swing.JLabel();
        Price_JLabel = new javax.swing.JLabel();
        Seats_JLabel = new javax.swing.JLabel();
        ID_JLabel = new javax.swing.JLabel();
        Description_JLabel = new javax.swing.JLabel();
        From_JTextField = new javax.swing.JTextField();
        Price_JTextField = new javax.swing.JTextField();
        Seats_JTextField = new javax.swing.JTextField();
        ID_JTextField = new javax.swing.JTextField();
        Description_JTextField = new javax.swing.JTextField();
        Back_JButton = new javax.swing.JButton();
        Create_JButton = new javax.swing.JButton();
        To_JTextField = new javax.swing.JTextField();
        PlaneName_JTextField = new javax.swing.JTextField();
        Description_JLabel1 = new javax.swing.JLabel();
        Description_JLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(660, 500));

        CreateAirplane_JLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CreateAirplane_JLabel.setText("Create Airplane");

        PlaneName_JLabel.setText("Plane Name:");

        Price_JLabel.setText("Price:");

        Seats_JLabel.setText("Seats Available:");

        ID_JLabel.setText("Plane ID:");

        Description_JLabel.setText("Description:");

        From_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                From_JTextFieldActionPerformed(evt);
            }
        });

        Price_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price_JTextFieldActionPerformed(evt);
            }
        });

        Seats_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seats_JTextFieldActionPerformed(evt);
            }
        });

        ID_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_JTextFieldActionPerformed(evt);
            }
        });

        Description_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Description_JTextFieldActionPerformed(evt);
            }
        });

        Back_JButton.setText("Back");
        Back_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_JButtonActionPerformed(evt);
            }
        });

        Create_JButton.setText("Create");
        Create_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_JButtonActionPerformed(evt);
            }
        });

        To_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                To_JTextFieldActionPerformed(evt);
            }
        });

        PlaneName_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaneName_JTextFieldActionPerformed(evt);
            }
        });

        Description_JLabel1.setText("From");

        Description_JLabel2.setText("To");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Description_JLabel)
                            .addComponent(ID_JLabel)
                            .addComponent(Seats_JLabel)
                            .addComponent(Price_JLabel)
                            .addComponent(PlaneName_JLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(CreateAirplane_JLabel))
                            .addComponent(PlaneName_JTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Back_JButton)
                            .addComponent(Description_JLabel1)
                            .addComponent(Description_JLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Create_JButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(From_JTextField)
                            .addComponent(Seats_JTextField)
                            .addComponent(ID_JTextField)
                            .addComponent(Description_JTextField)
                            .addComponent(Price_JTextField)
                            .addComponent(To_JTextField))))
                .addGap(232, 232, 232))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateAirplane_JLabel)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaneName_JLabel)
                    .addComponent(PlaneName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price_JLabel)
                    .addComponent(Price_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seats_JLabel)
                    .addComponent(Seats_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_JLabel)
                    .addComponent(ID_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Description_JLabel)
                    .addComponent(Description_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(From_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description_JLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(To_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description_JLabel2))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_JButton)
                    .addComponent(Create_JButton))
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Price_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price_JTextFieldActionPerformed

    private void From_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_From_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_From_JTextFieldActionPerformed

    private void Seats_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seats_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Seats_JTextFieldActionPerformed

    private void ID_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_JTextFieldActionPerformed

    private void Description_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Description_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Description_JTextFieldActionPerformed

    private void Back_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_JButtonActionPerformed
        // TODO add your handling code here:
        Display_JPanel.remove(this);
        CardLayout layout=(CardLayout)Display_JPanel.getLayout();
        layout.previous(Display_JPanel);
        
    }//GEN-LAST:event_Back_JButtonActionPerformed

    private void Create_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_JButtonActionPerformed
        // TODO add your handling code here:
       
        try{ 
        Airplane airplane=airliner.getAirplanecatalog().addAirplane();
        
        airplane.setPlaneName(PlaneName_JTextField.getText());
        airplane.setPrice(Float.parseFloat(Price_JTextField.getText()));
        Float.parseFloat(Price_JTextField.getText());
        airplane.setSeats(Integer.parseInt(Seats_JTextField.getText()));
        Integer.parseInt(Seats_JTextField.getText());
        airplane.setPlaneID(Integer.parseInt(ID_JTextField.getText()));
        Integer.parseInt(ID_JTextField.getText());
        airplane.setDescription(Description_JTextField.getText());
        airplane.setFrom(From_JTextField.getText());
        airplane.setTo(To_JTextField.getText());
          if(Seats_JTextField.getText().isEmpty()||From_JTextField.getText().isEmpty()||To_JTextField.getText().isEmpty()||Description_JTextField.getText().isEmpty()||ID_JTextField.getText().isEmpty()||Price_JTextField.getText().isEmpty()||PlaneName_JTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please add all the Values");
         
            }
       else{    
            JOptionPane.showMessageDialog(null, "Airliner Created Successfully");
            } 
        
        PlaneName_JTextField.setText("");
        Price_JTextField.setText("");
        Seats_JTextField.setText("");
        ID_JTextField.setText("");
        Description_JTextField.setText("");
        From_JTextField.setText("");
        To_JTextField.setText("");
            }
        catch(Exception e){
                   JOptionPane.showMessageDialog(null,"Invalid values");
        }
        
    }//GEN-LAST:event_Create_JButtonActionPerformed

    private void To_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_To_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_To_JTextFieldActionPerformed

    private void PlaneName_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaneName_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaneName_JTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_JButton;
    private javax.swing.JLabel CreateAirplane_JLabel;
    private javax.swing.JButton Create_JButton;
    private javax.swing.JLabel Description_JLabel;
    private javax.swing.JLabel Description_JLabel1;
    private javax.swing.JLabel Description_JLabel2;
    private javax.swing.JTextField Description_JTextField;
    private javax.swing.JTextField From_JTextField;
    private javax.swing.JLabel ID_JLabel;
    private javax.swing.JTextField ID_JTextField;
    private javax.swing.JLabel PlaneName_JLabel;
    private javax.swing.JTextField PlaneName_JTextField;
    private javax.swing.JLabel Price_JLabel;
    private javax.swing.JTextField Price_JTextField;
    private javax.swing.JLabel Seats_JLabel;
    private javax.swing.JTextField Seats_JTextField;
    private javax.swing.JTextField To_JTextField;
    // End of variables declaration//GEN-END:variables
}
