/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageAirplaneUserInterface;
import Business.Airliner;
import Business.Airplane;
import Business.AirplaneCatalog;
import Business.AirlinerCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rusha
 */

public class ManageViewAirplane_JPanel extends javax.swing.JPanel {
private AirplaneCatalog airplanecatalog;
private Airplane airplane;
private AirlinerCatalog airlinercatalog;
private Airliner airliner;
private JPanel Display_JPanel;

    /**
     * Creates new form ManageView_JPanel
     */
    public ManageViewAirplane_JPanel(JPanel Display_JPanel, Airliner airliner) {
        initComponents();
        this.Display_JPanel=Display_JPanel;
        this.airliner=airliner;
        this.airplane=new Airplane();
        this.airplanecatalog=new AirplaneCatalog();
        this.airlinercatalog=new AirlinerCatalog();
        
        
        AirlinerName_JTextField.setText(airliner.getAirlinerName());
        
        refreshTable();
    }

        public void refreshTable(){
        int rowCount=View_JTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)View_JTable.getModel();
        //dtm.setRowCount(0);
        for(int i=rowCount-1;i>=0;i--){
        dtm.removeRow(i);
        }
        
        for(Airplane airplane : airliner.getAirplanecatalog().getAirplaneCatalog()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=airplane;
            row[1]=airplane.getPrice();
            row[2]=airplane.getFrom();
            row[3]=airplane.getTo();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageView_JLabel = new javax.swing.JLabel();
        JScrollPane = new javax.swing.JScrollPane();
        View_JTable = new javax.swing.JTable();
        Search_JLabel = new javax.swing.JLabel();
        Search_JTextfield = new javax.swing.JTextField();
        Delete_JButton = new javax.swing.JButton();
        Back_JButton = new javax.swing.JButton();
        ViewDetails_JButton = new javax.swing.JButton();
        AirlinerName_JLabel = new javax.swing.JLabel();
        AirlinerName_JTextField = new javax.swing.JTextField();

        ManageView_JLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManageView_JLabel.setText("Manage/View Airplane");

        View_JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Name ", "Price", "From", "To"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        View_JTable.getTableHeader().setReorderingAllowed(false);
        JScrollPane.setViewportView(View_JTable);

        Search_JLabel.setText("Search Keyword");

        Search_JTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Search_JTextfieldKeyTyped(evt);
            }
        });

        Delete_JButton.setText("Delete Product");
        Delete_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_JButtonActionPerformed(evt);
            }
        });

        Back_JButton.setText("Back");
        Back_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_JButtonActionPerformed(evt);
            }
        });

        ViewDetails_JButton.setText("ViewDetails");
        ViewDetails_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetails_JButtonActionPerformed(evt);
            }
        });

        AirlinerName_JLabel.setText("Airliner Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back_JButton)
                        .addGap(114, 114, 114)
                        .addComponent(ViewDetails_JButton))
                    .addComponent(Delete_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Search_JLabel)
                            .addGap(18, 18, 18)
                            .addComponent(Search_JTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(AirlinerName_JLabel)
                            .addGap(18, 18, 18)
                            .addComponent(AirlinerName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageView_JLabel))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(ManageView_JLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AirlinerName_JLabel)
                            .addComponent(AirlinerName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_JLabel)
                    .addComponent(Search_JTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Delete_JButton)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_JButton)
                    .addComponent(ViewDetails_JButton))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Search_JTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_JTextfieldKeyTyped
        // TODO add your handling code here:
        DefaultTableModel SearchTableOutput = (DefaultTableModel)View_JTable.getModel();
        
        String search=Search_JTextfield.getText();
        TableRowSorter<DefaultTableModel> SearchTableSort = new TableRowSorter<DefaultTableModel>(SearchTableOutput);
        View_JTable.setRowSorter(SearchTableSort);
        SearchTableSort.setRowFilter(RowFilter.regexFilter(search));

        /*SearchTableOutput.setRowCount(0);
        for(Product a:prodDir.getProductDirectory()){
            if(searchTextfield.getText().equals(a.getName())){
                Object[] row = new Object[SearchTableOutput.getColumnCount()];
                row[0]=a;
                row[1]=a.getAvailNum();
                row[2]=a.getPrice();
                SearchTableOutput.addRow(row);
            }
        }*/
    }//GEN-LAST:event_Search_JTextfieldKeyTyped

    private void Delete_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_JButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = View_JTable.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Airplane airplane = (Airplane)View_JTable.getValueAt(selectedRow, 0);
                airplanecatalog.removeAirplane(airplane);
                refreshTable();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_Delete_JButtonActionPerformed

    private void Back_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_JButtonActionPerformed
        // TODO add your handling code here:
        Display_JPanel.remove(this);
        CardLayout cardLayout=(CardLayout)Display_JPanel.getLayout();
        cardLayout.previous(Display_JPanel);
    }//GEN-LAST:event_Back_JButtonActionPerformed

    private void ViewDetails_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetails_JButtonActionPerformed
        // TODO add your handling code here:
        int SelectedRow=View_JTable.getSelectedRow();

        if(SelectedRow>=0){
            Airplane airplane=(Airplane)View_JTable.getValueAt(SelectedRow, 0);
            ViewAirplane_JPanel vPanel=new ViewAirplane_JPanel(Display_JPanel,airplane);
            Display_JPanel.add("ViewPanel",vPanel);
            CardLayout layout=(CardLayout) Display_JPanel.getLayout();
            layout.next(Display_JPanel);}
        else{
            JOptionPane.showMessageDialog(null,"Please Select a Row!");
        }

    }//GEN-LAST:event_ViewDetails_JButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AirlinerName_JLabel;
    private javax.swing.JTextField AirlinerName_JTextField;
    private javax.swing.JButton Back_JButton;
    private javax.swing.JButton Delete_JButton;
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JLabel ManageView_JLabel;
    private javax.swing.JLabel Search_JLabel;
    private javax.swing.JTextField Search_JTextfield;
    private javax.swing.JButton ViewDetails_JButton;
    private javax.swing.JTable View_JTable;
    // End of variables declaration//GEN-END:variables
}
