/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageUserInterface;
import javax.swing.JOptionPane;
import Business.AirplaneCatalog;
import Business.Airplane;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author rusha
 */
public class ViewAirplane_JPanel extends javax.swing.JPanel {
private AirplaneCatalog airplanecatalog;
private JPanel Display_JPanel;
private Airplane airplane;
    /**
     * Creates new form ViewAirplane_JPanel
     */
    public ViewAirplane_JPanel(JPanel Display_JPanel, Airplane airplane, AirplaneCatalog airplanecatalog) {
        initComponents();
        this.airplane=airplane;
        this.airplanecatalog=airplanecatalog;
        this.Display_JPanel=Display_JPanel;
        PlaneName_JTextField.setText(airplane.getPlaneName());
        Price_JTextField.setText(String.valueOf(airplane.getPrice()));
        Seats_JTextField.setText(String.valueOf(airplane.getSeats()));
        ID_JTextField.setText(String.valueOf(airplane.getPlaneID()));
        Description_JTextField.setText(airplane.getDescription());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewAirplane_JLabel = new javax.swing.JLabel();
        PlaneName_JLabel = new javax.swing.JLabel();
        PlaneName_JTextField = new javax.swing.JTextField();
        Price_JLabel = new javax.swing.JLabel();
        Price_JTextField = new javax.swing.JTextField();
        Seats_JLabel = new javax.swing.JLabel();
        Seats_JTextField = new javax.swing.JTextField();
        ID_JLabel = new javax.swing.JLabel();
        ID_JTextField = new javax.swing.JTextField();
        Description_JLabel = new javax.swing.JLabel();
        Description_JTextField = new javax.swing.JTextField();
        Back_JButton = new javax.swing.JButton();
        Save_JButton = new javax.swing.JButton();
        Update_JButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(660, 500));

        ViewAirplane_JLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ViewAirplane_JLabel.setText("View Airplane");

        PlaneName_JLabel.setText("Plane Name:");

        PlaneName_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaneName_JTextFieldActionPerformed(evt);
            }
        });

        Price_JLabel.setText("Price:");

        Price_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price_JTextFieldActionPerformed(evt);
            }
        });

        Seats_JLabel.setText("Seats:");

        Seats_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seats_JTextFieldActionPerformed(evt);
            }
        });

        ID_JLabel.setText("Plane ID:");

        ID_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_JTextFieldActionPerformed(evt);
            }
        });

        Description_JLabel.setText("Description:");

        Description_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Description_JTextFieldActionPerformed(evt);
            }
        });

        Back_JButton.setText("Back");
        Back_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_JButtonActionPerformed(evt);
            }
        });

        Save_JButton.setText("Save");
        Save_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_JButtonActionPerformed(evt);
            }
        });

        Update_JButton.setText("Update");
        Update_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Description_JLabel)
                            .addComponent(ID_JLabel)
                            .addComponent(Seats_JLabel)
                            .addComponent(Price_JLabel)
                            .addComponent(PlaneName_JLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back_JButton)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlaneName_JTextField)
                            .addComponent(Seats_JTextField)
                            .addComponent(ID_JTextField)
                            .addComponent(Description_JTextField)
                            .addComponent(Price_JTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Save_JButton)
                                .addGap(18, 18, 18)
                                .addComponent(Update_JButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ViewAirplane_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))))
                .addGap(232, 232, 232))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewAirplane_JLabel)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaneName_JLabel)
                    .addComponent(PlaneName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price_JLabel)
                    .addComponent(Price_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seats_JLabel)
                    .addComponent(Seats_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_JLabel)
                    .addComponent(ID_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Description_JLabel)
                    .addComponent(Description_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save_JButton)
                    .addComponent(Back_JButton)
                    .addComponent(Update_JButton))
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Description_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Description_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Description_JTextFieldActionPerformed

    private void ID_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_JTextFieldActionPerformed

    private void Seats_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seats_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Seats_JTextFieldActionPerformed

    private void Price_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price_JTextFieldActionPerformed

    private void PlaneName_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaneName_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaneName_JTextFieldActionPerformed

    private void Back_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_JButtonActionPerformed
        // TODO add your handling code here:
        Display_JPanel.remove(this);
        CardLayout layout=(CardLayout)Display_JPanel.getLayout();
        layout.previous(Display_JPanel);
        
    }//GEN-LAST:event_Back_JButtonActionPerformed

    private void Update_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_JButtonActionPerformed
        // TODO add your handling code here:
        PlaneName_JTextField.setEditable(true);
        Price_JTextField.setEditable(true);
        Seats_JTextField.setEditable(true);
        ID_JTextField.setEditable(true);
        Description_JTextField.setEditable(true);
        Save_JButton.setEnabled(true);
        Update_JButton.setEnabled(false);
        
    }//GEN-LAST:event_Update_JButtonActionPerformed

    private void Save_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_JButtonActionPerformed
        // TODO add your handling code here:
        
        PlaneName_JTextField.setEditable(false);
        Price_JTextField.setEditable(false);
        Seats_JTextField.setEditable(false);
        ID_JTextField.setEditable(false);
        Description_JTextField.setEditable(false);
        Save_JButton.setEnabled(false);
        Update_JButton.setEnabled(true);
        
        try{
        airplane.setPlaneName(PlaneName_JTextField.getText());
        airplane.setPrice(Float.parseFloat(Price_JTextField.getText()));
        airplane.setSeats(Integer.parseInt(Seats_JTextField.getText()));
        airplane.setPlaneID(Integer.parseInt(ID_JTextField.getText()));
        airplane.setDescription(Description_JTextField.getText());
        if(PlaneName_JTextField.getText().isEmpty()||Price_JTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please add all the Values");
            }
        else{    
            JOptionPane.showMessageDialog(null, "Airliner Created Successfully");
            }
        }
        catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Invalid values");
        }
    }//GEN-LAST:event_Save_JButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_JButton;
    private javax.swing.JLabel Description_JLabel;
    private javax.swing.JTextField Description_JTextField;
    private javax.swing.JLabel ID_JLabel;
    private javax.swing.JTextField ID_JTextField;
    private javax.swing.JLabel PlaneName_JLabel;
    private javax.swing.JTextField PlaneName_JTextField;
    private javax.swing.JLabel Price_JLabel;
    private javax.swing.JTextField Price_JTextField;
    private javax.swing.JButton Save_JButton;
    private javax.swing.JLabel Seats_JLabel;
    private javax.swing.JTextField Seats_JTextField;
    private javax.swing.JButton Update_JButton;
    private javax.swing.JLabel ViewAirplane_JLabel;
    // End of variables declaration//GEN-END:variables
}
