/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import javax.swing.JOptionPane;
import Business.ProductDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;


/**
 *
 * @author info
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    //private ProductDirectory prodDir;
    private Product product;
      private ProductDirectory accDir;
    private JPanel rightPanel;
   

    
    ViewPanel(JPanel rightPanel, Product prod, ProductDirectory accDir) {
        initComponents();
        this.product=prod;
        
        txtAvailablity.setText(String.valueOf(prod.getAvailNum()));
        txtPrice.setText(String.valueOf(prod.getPrice()));
        txtProdName.setText(prod.getName());
        txtDesc.setText(prod.getDescription());
        this.accDir = accDir;
        this.rightPanel=rightPanel;

    
    }
 

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrice = new javax.swing.JTextField();
        txtProdName = new javax.swing.JTextField();
        txtAvailablity = new javax.swing.JTextField();
        Price1_JLabel = new javax.swing.JLabel();
        ProductName_JLabel = new javax.swing.JLabel();
        Availability1_JLabel = new javax.swing.JLabel();
        lblHead = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        Description_JLabel = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        Availability_JLabel = new javax.swing.JLabel();
        Price_JLabel = new javax.swing.JLabel();
        Description_JLabel1 = new javax.swing.JLabel();
        ProductName_JLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));

        txtPrice.setEditable(false);
        txtPrice.setBackground(java.awt.Color.white);
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        txtProdName.setEditable(false);
        txtProdName.setBackground(java.awt.Color.white);
        txtProdName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProdNameKeyTyped(evt);
            }
        });

        txtAvailablity.setEditable(false);
        txtAvailablity.setBackground(java.awt.Color.white);
        txtAvailablity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAvailablityKeyTyped(evt);
            }
        });

        Price1_JLabel.setText("Price");

        ProductName_JLabel.setText("Product Name");

        Availability1_JLabel.setText("Availablity");

        lblHead.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHead.setText("View Product");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        Description_JLabel.setText("Description");

        txtDesc.setEditable(false);
        txtDesc.setBackground(new java.awt.Color(255, 255, 255));
        txtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescKeyTyped(evt);
            }
        });

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        Availability_JLabel.setBackground(new java.awt.Color(255, 51, 51));
        Availability_JLabel.setForeground(new java.awt.Color(102, 255, 204));

        Price_JLabel.setBackground(new java.awt.Color(255, 51, 51));
        Price_JLabel.setForeground(new java.awt.Color(102, 255, 204));

        Description_JLabel1.setBackground(new java.awt.Color(255, 51, 51));
        Description_JLabel1.setForeground(new java.awt.Color(102, 255, 204));

        ProductName_JLabel1.setBackground(new java.awt.Color(255, 51, 51));
        ProductName_JLabel1.setForeground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblHead)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ProductName_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Availability1_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Price1_JLabel)
                                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Description_JLabel))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAvailablity)
                            .addComponent(txtPrice)
                            .addComponent(txtProdName)
                            .addComponent(txtDesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Availability_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Price_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductName_JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Description_JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 98, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHead)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ProductName_JLabel)
                        .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ProductName_JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Availability1_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAvailablity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Price1_JLabel)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Availability_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38))
                                .addComponent(Price_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Description_JLabel)
                            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Description_JLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton)
                .addGap(0, 49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
            txtAvailablity.setEditable(true);
            txtPrice.setEditable(true);
            txtProdName.setEditable(true);
            txtDesc.setEditable(true);
            btnSave.setEnabled(true);
            btnUpdate.setEnabled(false);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
            txtAvailablity.setEditable(false);
            txtPrice.setEditable(false);
            txtProdName.setEditable(false);
            txtDesc.setEditable(false);
            btnSave.setEnabled(false);
            btnUpdate.setEnabled(true);
        
            try
           {
            product.setName(txtProdName.getText());
            product.setPrice(Double.parseDouble(txtPrice.getText()));
            product.setAvailNum(Integer.parseInt(txtAvailablity.getText()));
            product.setDescription(txtDesc.getText());
             if(txtProdName.getText().isEmpty()||txtAvailablity.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please add all the Values");
            }
            else{
            JOptionPane.showMessageDialog(null, "Account updated successfully"); 
             }
           }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,"Invalid values");
           } 
            
           
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout cardlayout=(CardLayout)rightPanel.getLayout();
        cardlayout.previous(rightPanel);
        
        Component [] components=rightPanel.getComponents();
        for(Component c : components){
            if(c instanceof ManageProdPanel){
                ManageProdPanel panel=(ManageProdPanel)c;
                panel.populate();
            }
        }
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void txtAvailablityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAvailablityKeyTyped
        // TODO add your handling code here:
        /*if(txtAvailablity.getText().trim().isEmpty()){
        Availability_JLabel.setText("Please add values");
        }
        int Availablity=Integer.parseInt(txtAvailablity.getText());      
        //Availability_JLabel.setText("");*/
        try{
        int Availablity=Integer.parseInt(txtAvailablity.getText());   
        Availability_JLabel.setText("");
        }
        catch(Exception e){
        Availability_JLabel.setText("Please Add Correct Availability");
        }
        
    }//GEN-LAST:event_txtAvailablityKeyTyped

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        // TODO add your handling code here:
        /*if(txtPrice.getText().trim().isEmpty()){
        Price_JLabel.setText("Please add values");
        }        
        double Price=Double.parseDouble(txtPrice.getText());      
        //Price_JLabel.setText("");*/
        try{
        double Price=Double.parseDouble(txtPrice.getText());      
        Price_JLabel.setText("");
        }  
        catch(Exception e){
              Price_JLabel.setText("Please Add Correct Price");
        }

    }//GEN-LAST:event_txtPriceKeyTyped

    private void txtProdNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdNameKeyTyped
        // TODO add your handling code here:
        
        if(txtProdName.getText().trim().isEmpty()){
        ProductName_JLabel1.setText("Please add values");
        }
        String ProdName=txtProdName.getText();      
        ProductName_JLabel1.setText("");
        
    }//GEN-LAST:event_txtProdNameKeyTyped

    private void txtDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyTyped
        // TODO add your handling code here:
        if(txtDesc.getText().trim().isEmpty()){
        Description_JLabel1.setText("Please add values");
        }
        String Description=txtDesc.getText();      
        Description_JLabel1.setText("");
        
    }//GEN-LAST:event_txtDescKeyTyped

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Availability1_JLabel;
    private javax.swing.JLabel Availability_JLabel;
    private javax.swing.JLabel Description_JLabel;
    private javax.swing.JLabel Description_JLabel1;
    private javax.swing.JLabel Price1_JLabel;
    private javax.swing.JLabel Price_JLabel;
    private javax.swing.JLabel ProductName_JLabel;
    private javax.swing.JLabel ProductName_JLabel1;
    private javax.swing.JButton backButton;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblHead;
    private javax.swing.JTextField txtAvailablity;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProdName;
    // End of variables declaration//GEN-END:variables

   
}
