/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUserInterface;
import Business.AirplaneCatalog;
import Business.AirlinerCatalog;
import ManageAirplaneUserInterface.AirlinerLogin_JPanel;
import ManageAirlinerUserInterface.ManageAirliner_JPanel;
import ManageAirplaneUserInterface.ManageAirplane_JPanel;
import MasterScheduleUserInterface.MasterSchedule_JPanel;
import java.awt.CardLayout;
/**
 *
 * @author rusha
 */


public class Main_JFrame extends javax.swing.JFrame {
//private AirplaneCatalog airplanecatalog;
private AirlinerCatalog airlinercatalog;
    /**
     * Creates new form Main_JFrame
     */
    public Main_JFrame() {
        initComponents();
//        airplanecatalog=new AirplaneCatalog();
        airlinercatalog=new AirlinerCatalog();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSplitPane = new javax.swing.JSplitPane();
        Control_JPanel = new javax.swing.JPanel();
        ManageAirplanes_JButton = new javax.swing.JButton();
        ManageAirliner_JButton = new javax.swing.JButton();
        MasterSchedule_JButton = new javax.swing.JButton();
        Display_JPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JSplitPane.setDividerLocation(100);
        JSplitPane.setLastDividerLocation(100);
        JSplitPane.setMinimumSize(new java.awt.Dimension(500, 300));

        Control_JPanel.setPreferredSize(new java.awt.Dimension(150, 500));

        ManageAirplanes_JButton.setText("Manage Airplanes");
        ManageAirplanes_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAirplanes_JButtonActionPerformed(evt);
            }
        });

        ManageAirliner_JButton.setText("Manage Airliner");
        ManageAirliner_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAirliner_JButtonActionPerformed(evt);
            }
        });

        MasterSchedule_JButton.setText("Master Schedule");
        MasterSchedule_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasterSchedule_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Control_JPanelLayout = new javax.swing.GroupLayout(Control_JPanel);
        Control_JPanel.setLayout(Control_JPanelLayout);
        Control_JPanelLayout.setHorizontalGroup(
            Control_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Control_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Control_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManageAirliner_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Control_JPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ManageAirplanes_JButton))
                    .addComponent(MasterSchedule_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Control_JPanelLayout.setVerticalGroup(
            Control_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Control_JPanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(ManageAirliner_JButton)
                .addGap(29, 29, 29)
                .addComponent(ManageAirplanes_JButton)
                .addGap(29, 29, 29)
                .addComponent(MasterSchedule_JButton)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        JSplitPane.setLeftComponent(Control_JPanel);

        Display_JPanel.setPreferredSize(new java.awt.Dimension(670, 500));
        Display_JPanel.setLayout(new java.awt.CardLayout());
        JSplitPane.setRightComponent(Display_JPanel);

        getContentPane().add(JSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageAirplanes_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAirplanes_JButtonActionPerformed
        // TODO add your handling code here:
        
        AirlinerLogin_JPanel airlinerloginjpanel =new AirlinerLogin_JPanel(Display_JPanel, airlinercatalog);
        Display_JPanel.add("AirlinerLogin_JPanel",airlinerloginjpanel);
                
    //    ManageAirplane_JPanel manageairplanejpanel = new ManageAirplane_JPanel(Display_JPanel, airplanecatalog);
    //    Display_JPanel.add("ManageAirplane_JPanel",manageairplanejpanel);
        CardLayout layout=(CardLayout)Display_JPanel.getLayout();
        layout.next(Display_JPanel);
    }//GEN-LAST:event_ManageAirplanes_JButtonActionPerformed

    private void ManageAirliner_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAirliner_JButtonActionPerformed
        // TODO add your handling code here:
        ManageAirliner_JPanel manageairlinerjpanel = new ManageAirliner_JPanel(Display_JPanel, airlinercatalog);
        
        Display_JPanel.add("ManageAirliner_JPanel",manageairlinerjpanel);
        CardLayout layout=(CardLayout)Display_JPanel.getLayout();
        layout.next(Display_JPanel);
    }//GEN-LAST:event_ManageAirliner_JButtonActionPerformed

    private void MasterSchedule_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasterSchedule_JButtonActionPerformed
        // TODO add your handling code here:
        MasterSchedule_JPanel masterschedulejpanel = new MasterSchedule_JPanel(Display_JPanel, airlinercatalog);
        
        Display_JPanel.add("MasterSchedule_JPanel",masterschedulejpanel);
        CardLayout layout=(CardLayout)Display_JPanel.getLayout();
        layout.next(Display_JPanel);
        
    }//GEN-LAST:event_MasterSchedule_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Control_JPanel;
    private javax.swing.JPanel Display_JPanel;
    private javax.swing.JSplitPane JSplitPane;
    private javax.swing.JButton ManageAirliner_JButton;
    private javax.swing.JButton ManageAirplanes_JButton;
    private javax.swing.JButton MasterSchedule_JButton;
    // End of variables declaration//GEN-END:variables
}
